### ISSUE TITLE
Bug in install_python command

### ISSUE THREAD

**Issue by Raul-Ciria-Aylagas** [urbanopt/urbanopt-cli#405]
### Expected behavior

The install_python command should install python locally in the example_files/python_deps folder.

### Actual behavior

The function install_python_dependencies calls to check_python before installing the local miniconda and python executables. Therefore the Open3.capture3 calls inside check_python fails because the executable paths doesn't exists.
A workaround is to manually execute the install_python.ps1 command in the example_files/python_deps folder, but this is nowhere in the docs.

### To Reproduce

Install UrbanOpt 0.9.1 with the installer, activate the environment and run "uo install_python". Output:

```
Installing python and dependencies
Checking system.....
Traceback (most recent call last):
        13: from C:/URBANopt-cli-0.9.1/gems/ruby/2.7.0/bin/uo:23:in `<main>'
        12: from C:/URBANopt-cli-0.9.1/gems/ruby/2.7.0/bin/uo:23:in `load'
        11: from C:/URBANopt-cli-0.9.1/gems/ruby/2.7.0/gems/urbanopt-cli-0.9.1/bin/uo:3:in `<top (required)>'
        10: from C:/URBANopt-cli-0.9.1/ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         9: from C:/URBANopt-cli-0.9.1/ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         8: from C:/URBANopt-cli-0.9.1/gems/ruby/2.7.0/gems/urbanopt-cli-0.9.1/lib/uo_cli.rb:57:in `<top (required)>'
         7: from C:/URBANopt-cli-0.9.1/gems/ruby/2.7.0/gems/urbanopt-cli-0.9.1/lib/uo_cli.rb:58:in `<module:URBANopt>'
         6: from C:/URBANopt-cli-0.9.1/gems/ruby/2.7.0/gems/urbanopt-cli-0.9.1/lib/uo_cli.rb:1214:in `<module:CLI>'
         5: from C:/URBANopt-cli-0.9.1/gems/ruby/2.7.0/gems/urbanopt-cli-0.9.1/lib/uo_cli.rb:1028:in `install_python_dependencies'
         4: from C:/URBANopt-cli-0.9.1/gems/ruby/2.7.0/gems/urbanopt-cli-0.9.1/lib/uo_cli.rb:955:in `check_python'
         3: from C:/URBANopt-cli-0.9.1/ruby/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from C:/URBANopt-cli-0.9.1/ruby/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/URBANopt-cli-0.9.1/ruby/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/URBANopt-cli-0.9.1/ruby/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - C:/URBANopt-cli-0.9.1/gems/ruby/2.7.0/gems/urbanopt-cli-0.9.1/example_files/python_deps/python-3.10/python.exe -V (Errno::ENOENT)
```

### Additional context

I'm running on Windows 11. UrbanOpt v0.9.1.

**Comment by vtnate** [comment]
Closed by #458
